@echo off
echo Создание виртуального окружения...
python -m venv venv
echo Активация виртуального окружения...
call venv\Scripts\activate
echo Установка зависимостей...
pip install -e .
echo Установка завершена. Для активации окружения в будущем используйте: venv\Scripts\activate